version: '3'

services:
  ai-chatbot:
    image: ai-chatbot:latest # 使用本地构建并传输的镜像
    env_file:
      - .env
    ports:
      - "3003:3003"
    restart: unless-stopped
    networks:
      - tools_default

networks:
  tools_default:
    external: true
